In [1]:
%matplotlib inline

In [2]:
import os 
import sys
import json
import pandas as pd
import numpy as np
import joblib
import matplotlib.pyplot as plt
import neurokit as nk
import scipy as sc
import math 
import scipy.signal as ss
import warnings
import itertools

from scipy import signal
warnings.filterwarnings('ignore')

In [ ]:
path = "/mnt/shared_drive/data/brain_therapy/Brain_Therapy_MVP_Content_Pilot/FA_corrected_signals"
files = os.listdir(path)

In [ ]:
sensor_data = pd.DataFrame([])
for file in files:
    data = pd.read_csv(os.path.join(path,file))
    data['Participant'] = file.split("-")[3].split(".")[0]
    data['Datetime'] = pd.to_datetime(data['Datetime'])
    data.set_index(['Participant','Datetime'], inplace = True)
    sensor_data = pd.concat([sensor_data,data])

In [ ]:
participants = sensor_data.index.get_level_values('Participant').unique().values
participants = sorted(participants)
sensor_data.sort_index(sort_remaining = True, inplace = True)
sensor_data.head()

In [3]:
log_events = joblib.load("/mnt/shared_drive/data/brain_therapy/log_events.pkl")

In [4]:
log_events = log_events.reset_index().rename(columns = {'participant':"Participant", "time":"Datetime"}).set_index(["Participant","Datetime"])
log_events.head()

                                type           context
Participant Datetime
0001        2019-07-10 15:25:32   2D  StartFrontBuffer
            2019-07-10 15:27:32   2D   StopFrontBuffer
            2019-07-10 15:27:32   2D           StartLL
            2019-07-10 15:29:42   2D            StopLL
            2019-07-10 15:29:42   2D           StartHH

### Using the curated signals to compute features

In [5]:
curated_signals = joblib.load("/mnt/shared_drive/data/brain_therapy/Brain_Therapy_MVP_Content_Pilot/FA_corrected_signals_amplitude.pkl")

In [6]:
p = curated_signals.keys()
curated_df = pd.DataFrame([])
for part in p:
    data = curated_signals[part]
    data['Participant'] = part.split("-")[3]
    curated_df = pd.concat([curated_df,data])
curated_df.set_index(["Participant","Datetime"], inplace = True)
curated_df.head()

                                          RSP       PPG     1-SKTA       ECG  \
Participant Datetime
0001        2019-07-10 15:22:31.000 -1.263123  0.003052  12.941162 -0.234833
            2019-07-10 15:22:31.004 -1.261902  0.003662  12.945435 -0.226593
            2019-07-10 15:22:31.008 -1.264648  0.002136  12.946045 -0.215607
            2019-07-10 15:22:31.012 -1.261902  0.003662  12.945435 -0.206604
            2019-07-10 15:22:31.016 -1.262207  0.003357  12.946045 -0.198364

                                          EDA
Participant Datetime
0001        2019-07-10 15:22:31.000  0.041124
            2019-07-10 15:22:31.004  0.042649
            2019-07-10 15:22:31.008  0.044175
            2019-07-10 15:22:31.012  0.039598
            2019-07-10 15:22:31.016  0.042649

In [7]:
temp_df = curated_df.merge(log_events, how = "left", right_index = True, left_index = True)

In [222]:
t = temp_df.copy()

In [223]:
t['context'] = t['context'].ffill()
t['type'] = t['type'].ffill()
t['context'] = t['context'].fillna("Garbage")
t['type'] = t['type'].fillna("Garbage")

In [224]:
# t = t[pd.notnull(t['context'])]
t = t.reset_index().set_index(["Participant","type","context","Datetime"])
t.head()

                                                          RSP       PPG  \
Participant type    context Datetime
0001        Garbage Garbage 2019-07-10 15:22:31.000 -1.263123  0.003052
                            2019-07-10 15:22:31.004 -1.261902  0.003662
                            2019-07-10 15:22:31.008 -1.264648  0.002136
                            2019-07-10 15:22:31.012 -1.261902  0.003662
                            2019-07-10 15:22:31.016 -1.262207  0.003357

                                                        1-SKTA       ECG  \
Participant type    context Datetime
0001        Garbage Garbage 2019-07-10 15:22:31.000  12.941162 -0.234833
                            2019-07-10 15:22:31.004  12.945435 -0.226593
                            2019-07-10 15:22:31.008  12.946045 -0.215607
                            2019-07-10 15:22:31.012  12.945435 -0.206604
                            2019-07-10 15:22:31.016  12.946045 -0.198364

                                                          EDA
Participant type    context Datetime
0001        Garbage Garbage 2019-07-10 15:22:31.000  0.041124
                            2019-07-10 15:22:31.004  0.042649
                            2019-07-10 15:22:31.008  0.044175
                            2019-07-10 15:22:31.012  0.039598
                            2019-07-10 15:22:31.016  0.042649

In [73]:
x_temp = t.copy()
x_temp.reset_index("Datetime", inplace = True)
x_new = pd.DataFrame(x_temp[["Datetime"]].groupby(["Participant","type","context"]).apply(lambda x: x['Datetime'].values[0]), columns = ["time_zero"])

In [74]:
x_new.head()
x_temp.head()

                                           Datetime       RSP       PPG  \
Participant type    context
0001        Garbage Garbage 2019-07-10 15:22:31.000 -1.263123  0.003052
                    Garbage 2019-07-10 15:22:31.004 -1.261902  0.003662
                    Garbage 2019-07-10 15:22:31.008 -1.264648  0.002136
                    Garbage 2019-07-10 15:22:31.012 -1.261902  0.003662
                    Garbage 2019-07-10 15:22:31.016 -1.262207  0.003357

                                1-SKTA       ECG       EDA
Participant type    context
0001        Garbage Garbage  12.941162 -0.234833  0.041124
                    Garbage  12.945435 -0.226593  0.042649
                    Garbage  12.946045 -0.215607  0.044175
                    Garbage  12.945435 -0.206604  0.039598
                    Garbage  12.946045 -0.198364  0.042649

In [94]:
x_new2 = x_temp.merge(x_new, how = "left", right_index = True, left_index = True)
x_new2["Datetime_sub"] = x_new2["Datetime"] - x_new2["time_zero"]
x_new2.set_index(["Datetime_sub","Datetime"], append = True, inplace = True)
t = x_new2.copy()

In [227]:
t.head()

                                                                              RSP  \
Participant type context        Datetime_sub    Datetime
0001        2D   StartEndBuffer 00:00:00        2019-07-10 15:36:12.000 -0.807800
                                00:00:00.004000 2019-07-10 15:36:12.004 -0.794067
                                00:00:00.008000 2019-07-10 15:36:12.008 -0.787659
                                00:00:00.012000 2019-07-10 15:36:12.012 -0.779114
                                00:00:00.016000 2019-07-10 15:36:12.016 -0.772705

                                                                              PPG  \
Participant type context        Datetime_sub    Datetime
0001        2D   StartEndBuffer 00:00:00        2019-07-10 15:36:12.000  0.002441
                                00:00:00.004000 2019-07-10 15:36:12.004  0.003052
                                00:00:00.008000 2019-07-10 15:36:12.008  0.003357
                                00:00:00.012000 2019-07-10 15:36:12.012  0.003052
                                00:00:00.016000 2019-07-10 15:36:12.016  0.002747

                                                                            1-SKTA  \
Participant type context        Datetime_sub    Datetime
0001        2D   StartEndBuffer 00:00:00        2019-07-10 15:36:12.000  12.976562
                                00:00:00.004000 2019-07-10 15:36:12.004  12.979004
                                00:00:00.008000 2019-07-10 15:36:12.008  12.977173
                                00:00:00.012000 2019-07-10 15:36:12.012  12.979004
                                00:00:00.016000 2019-07-10 15:36:12.016  12.978394

                                                                              ECG  \
Participant type context        Datetime_sub    Datetime
0001        2D   StartEndBuffer 00:00:00        2019-07-10 15:36:12.000 -0.327148
                                00:00:00.004000 2019-07-10 15:36:12.004 -0.327454
                                00:00:00.008000 2019-07-10 15:36:12.008 -0.327148
                                00:00:00.012000 2019-07-10 15:36:12.012 -0.327454
                                00:00:00.016000 2019-07-10 15:36:12.016 -0.323334

                                                                              EDA  \
Participant type context        Datetime_sub    Datetime
0001        2D   StartEndBuffer 00:00:00        2019-07-10 15:36:12.000  3.355333
                                00:00:00.004000 2019-07-10 15:36:12.004  3.355333
                                00:00:00.008000 2019-07-10 15:36:12.008  3.356858
                                00:00:00.012000 2019-07-10 15:36:12.012  3.359910
                                00:00:00.016000 2019-07-10 15:36:12.016  3.358384

                                                                                  time_zero
Participant type context        Datetime_sub    Datetime
0001        2D   StartEndBuffer 00:00:00        2019-07-10 15:36:12.000 2019-07-10 15:36:12
                                00:00:00.004000 2019-07-10 15:36:12.004 2019-07-10 15:36:12
                                00:00:00.008000 2019-07-10 15:36:12.008 2019-07-10 15:36:12
                                00:00:00.012000 2019-07-10 15:36:12.012 2019-07-10 15:36:12
                                00:00:00.016000 2019-07-10 15:36:12.016 2019-07-10 15:36:12

# ECG

In [81]:
participants = t.index.get_level_values("Participant").unique()

In [82]:
good_peaks = joblib.load("/mnt/shared_drive/data/brain_therapy/MVP_Focused_Attention/FA_r_peaks_index.pkl")

Computing ECG Heart Rate and Heart Rate Variability

In [233]:
ecg_hr_features = pd.DataFrame([])
ecg_hrv_features = pd.DataFrame([])
time_diff_df = pd.DataFrame([])
for participant in participants:
    data = t.loc(axis = 0)[participant,:,:,:,:]
    ecg_peaks = good_peaks["BT-MVP-FA-{}".format(participant)]
    time_stamps = data.index.get_level_values('Datetime')[ecg_peaks]
    d = data.loc(axis = 0)[participant,:,:,:,time_stamps]
    
    
    #Computing time differences
    try:
        d['time_differences'] = np.concatenate([np.diff(time_stamps)/np.timedelta64(1,'ms'), [0]])
    except:
        d['time_differences'] = np.concatenate([np.diff(time_stamps)/np.timedelta64(1,'ms'), [0,0]])

    d = d[['time_differences']]
    #Taking out time differences that is more than a minute
    df = d[d.time_differences<60000]
    diff_mean = np.mean(df.time_differences)
    upper_threshold = diff_mean + (3*np.std(df.time_differences))
    lower_threshold = diff_mean - (3*np.std(df.time_differences))
    df = df[(df.time_differences<upper_threshold) & (df.time_differences>lower_threshold)]
    
    # Drop NaN contexts
    temp = df.reset_index("context")
    temp = temp[pd.notnull(temp['context'])]
#     display(temp)
    df = temp.reset_index().set_index(["Participant","type","context","Datetime","Datetime_sub"])
    time_diff_df = pd.concat([time_diff_df, df])
    

#     break

In [243]:
time_diff_df.head()

                                                               Datetime  \
Participant type context        Datetime_sub
0001        2D   StartEndBuffer 00:00:00.700000 2019-07-10 15:36:12.700
                                00:00:01.764000 2019-07-10 15:36:13.764
                                00:00:02.788000 2019-07-10 15:36:14.788
                                00:00:03.804000 2019-07-10 15:36:15.804
                                00:00:04.840000 2019-07-10 15:36:16.840

                                                 time_differences
Participant type context        Datetime_sub
0001        2D   StartEndBuffer 00:00:00.700000            1064.0
                                00:00:01.764000            1024.0
                                00:00:02.788000            1016.0
                                00:00:03.804000            1036.0
                                00:00:04.840000             940.0

In [261]:
y_temp = time_diff_df.reset_index("Datetime_sub")
y_new = pd.DataFrame(y_temp[["Datetime_sub"]].groupby(["Participant","type","context"]).apply(lambda x: x['Datetime_sub'].values[0]),
                     columns = ["time_zero"])
y_new2 = y_temp.merge(y_new, how = "left", right_index = True, left_index = True)
y_new2["Datetime_sub"] = y_new2["Datetime_sub"] - y_new2["time_zero"]
y_new2.set_index(["Datetime_sub","Datetime"], append = True, inplace = True)
time_diff_new = y_new2.copy()

In [262]:
time_diff_new.head()

                                                                         time_differences  \
Participant type context        Datetime_sub    Datetime
0001        2D   StartEndBuffer 00:00:00        2019-07-10 15:36:12.700            1064.0
                                00:00:01.064000 2019-07-10 15:36:13.764            1024.0
                                00:00:02.088000 2019-07-10 15:36:14.788            1016.0
                                00:00:03.104000 2019-07-10 15:36:15.804            1036.0
                                00:00:04.140000 2019-07-10 15:36:16.840             940.0

                                                                              time_zero
Participant type context        Datetime_sub    Datetime
0001        2D   StartEndBuffer 00:00:00        2019-07-10 15:36:12.700 00:00:00.700000
                                00:00:01.064000 2019-07-10 15:36:13.764 00:00:00.700000
                                00:00:02.088000 2019-07-10 15:36:14.788 00:00:00.700000
                                00:00:03.104000 2019-07-10 15:36:15.804 00:00:00.700000
                                00:00:04.140000 2019-07-10 15:36:16.840 00:00:00.700000

In [270]:
ecg_hr_features = time_diff_new.groupby(["Participant","type","context",pd.Grouper(freq = "5s", level = "Datetime_sub")], sort = True).mean()
ecg_hr_features['ecg_heart_rate'] = (60/ecg_hr_features['time_differences'])*1000
ecg_hr_features.drop("time_differences",axis = 1, inplace = True)
ecg_hr_features.head()

                                              ecg_heart_rate
Participant type context        Datetime_sub
0001        2D   StartEndBuffer 00:00:00           59.055118
                                00:00:05           61.813187
                                00:00:10           62.866723
                                00:00:15           64.655172
                                00:00:20           74.196208

In [267]:
ecg_hrv_features = time_diff_new.groupby(["Participant","type","context",pd.Grouper(freq = "20s", level = "Datetime_sub")], sort = True).std()
ecg_hrv_features.rename(columns = {"time_differences":"ecg_hrv_std"}, inplace = True)
ecg_hrv_features.head()

                                              ecg_hrv_std
Participant type context        Datetime_sub
0001        2D   StartEndBuffer 00:00:00        70.691281
                                00:00:20        64.967976
                                00:00:40        55.276714
                                00:01:00        48.497066
                                00:01:20        91.838782

# Skin Temperature

In [119]:
skin_temperature = t[['1-SKTA']]
skin_temperature = skin_temperature.groupby(["Participant","type","context", pd.Grouper(freq = "10s", level = "Datetime_sub")]).mean()
skin_temperature.rename(columns = {"1-SKTA":"skin_temperature"}, inplace = True)
display(skin_temperature.head())

                                              skin_temperature
Participant type context        Datetime_sub
0001        2D   StartEndBuffer 00:00:00             12.967830
                                00:00:10             12.959119
                                00:00:20             12.959495
                                00:00:30             12.967094
                                00:00:40             12.966464

In [120]:
len(skin_temperature.loc(axis = 0)["0021","2D","StartLL",:])

13

# EDA

In [121]:
#EDA MEAN
eda_features = t[['EDA']]
eda_features = eda_features.groupby(["Participant","type","context", pd.Grouper(freq = "30s", level = "Datetime_sub")]).mean()
eda_features.rename(columns = {"EDA":"eda_mean"}, inplace = True)
display(eda_features.head())

                                                eda_mean
Participant type context          Datetime_sub
0001        2D   StartEndBuffer   00:00:00      3.677715
                                  00:00:30      5.122383
                                  00:01:00      5.102888
                                  00:01:30      5.220675
                 StartFrontBuffer 00:00:00      5.467291

In [122]:
len(skin_temperature.loc(axis = 0)["0001","3D","StartLL",:])

13

In [125]:
def get_eda_features(eda):
    if len(eda > 15):
        try:
            features = nk.eda_process(eda = eda, sampling_rate = 250)
        except:
#             print("No peaks here")
            return 0
    else:
        return 0
    peaks = len(features['EDA']['SCR_Peaks_Indexes'])
    return peaks

In [126]:
#Number of peaks 
eda_peaks_df = pd.DataFrame([])
for participant in participants:
    data = t.loc(axis = 0)[participant,:,:,:]
#     display(data.head())
    d = data['EDA'].groupby(["Participant","type","context", pd.Grouper(freq = '30s', level = "Datetime_sub")]).apply(lambda x: get_eda_features(x))
    d = pd.DataFrame(d)
    eda_peaks_df = pd.concat([eda_peaks_df, d])
# t['EDA'].groupby(["Participant","type","context", pd.Grouper(freq = '30s', level = "Datetime_sub")]).apply(lambda x: get_eda_features(x))

In [127]:
eda_peaks_df.rename(columns = {"EDA":"eda_no_of_peaks"}, inplace = True)
eda_features = eda_features.merge(eda_peaks_df, how = "left",right_index = True, left_index = True)

In [128]:
eda_features.head()

                                                eda_mean  eda_no_of_peaks
Participant type context          Datetime_sub
0001        2D   StartEndBuffer   00:00:00      3.677715                6
                                  00:00:30      5.122383                4
                                  00:01:00      5.102888                3
                                  00:01:30      5.220675                7
                 StartFrontBuffer 00:00:00      5.467291                3

In [ ]:
def compute_power_spectra(signal, band):
    try:
        x = np.fft.fft(signal - np.nanmean(signal))
        x = np.abs(x)
        freq = np.fft.fftfreq(len(signal), d = 0.004)
    except:
        return 0
    low, high = np.array(band)
    vals = [i for i in x if high>i>low]
    idx = [list(x).index(i) for i in vals]

    frequencies = freq[idx]
    power = np.sum((frequencies/len(signal))**2)
    return power

In [129]:
def compute_frequency_band_power(signal, band, sampling_rate):
    freq, power = ss.periodogram(signal - np.nanmean(signal), sampling_rate)
    low_f1, low_f2, high_f1, high_f2 = np.array(band)
    lfp_idx  = np.where((freq>=low_f1) & (freq>=low_f2))[0]
    hfp_idx  = np.where((freq>=high_f1) & (freq>=high_f2))[0] 
    lfp = np.trapz(power[lfp_idx], x = freq[lfp_idx])
    hfp = np.trapz(power[hfp_idx], x = freq[hfp_idx])
    
    return [lfp, hfp, lfp/hfp]

In [214]:
#High Frequecy and Low Frequency
bands =  [0.045, 0.15, 0.15,0.25]
eda_powers_df = pd.DataFrame([])
for participant in participants:
    data = t.loc(axis = 0)[participant,:,:,:]
    eda_powers = data["EDA"].groupby(["Participant","type","context",pd.Grouper(freq = "30s", level = "Datetime_sub")]).\
                apply(lambda x:compute_frequency_band_power(x,bands,250) if len(x)>1 else pd.Series(np.nan))
    eda_powers = pd.DataFrame(eda_powers)
    eda_powers = pd.DataFrame(list(eda_powers["EDA"].values), index = eda_powers.index, 
                              columns = ["eda_lf","eda_hf","eda_lf_hf_ratio"])
    eda_powers_df = pd.concat([eda_powers_df, eda_powers])

In [215]:
eda_powers_df.head()

                                                  eda_lf    eda_hf  \
Participant type context          Datetime_sub
0001        2D   StartEndBuffer   00:00:00      0.037592  0.023888
                                  00:00:30      0.001944  0.000539
                                  00:01:00      0.007135  0.002519
                                  00:01:30      0.006044  0.003774
                 StartFrontBuffer 00:00:00      0.025428  0.019284

                                                eda_lf_hf_ratio
Participant type context          Datetime_sub
0001        2D   StartEndBuffer   00:00:00             1.573690
                                  00:00:30             3.608991
                                  00:01:00             2.832421
                                  00:01:30             1.601694
                 StartFrontBuffer 00:00:00             1.318618

In [216]:
eda_features.drop(["eda_lf","eda_hf","eda_lf_hf_ratio"], axis = 1, inplace = True)

In [217]:
eda_features = eda_features.merge(eda_powers_df, how = 'left', right_index = True, left_index = True)

In [218]:
eda_features.head()

                                                eda_mean  eda_no_of_peaks  \
Participant type context          Datetime_sub
0001        2D   StartEndBuffer   00:00:00      3.677715                6
                                  00:00:30      5.122383                4
                                  00:01:00      5.102888                3
                                  00:01:30      5.220675                7
                 StartFrontBuffer 00:00:00      5.467291                3

                                                  eda_lf    eda_hf  \
Participant type context          Datetime_sub
0001        2D   StartEndBuffer   00:00:00      0.037592  0.023888
                                  00:00:30      0.001944  0.000539
                                  00:01:00      0.007135  0.002519
                                  00:01:30      0.006044  0.003774
                 StartFrontBuffer 00:00:00      0.025428  0.019284

                                                eda_lf_hf_ratio
Participant type context          Datetime_sub
0001        2D   StartEndBuffer   00:00:00             1.573690
                                  00:00:30             3.608991
                                  00:01:00             2.832421
                                  00:01:30             1.601694
                 StartFrontBuffer 00:00:00             1.318618

In [201]:
ecg_hr_features_v2 = ecg_hr_features.copy()
ecg_hr_features_v2.reset_index("Datetime_sub", inplace = True)
ecg_hr_features_v2["Datetime_sub"] = ecg_hr_features_v2["Datetime_sub"] / np.timedelta64(1, 's')
ecg_hr_features_v2['Datetime_sub'] = np.round(ecg_hr_features_v2['Datetime_sub'])
ecg_hr_features_v2['Datetime_sub'] = pd.to_timedelta(ecg_hr_features_v2['Datetime_sub'], unit = 's')
# ecg_hr_features_v2.head()
ecg_hr_features_v2.set_index("Datetime_sub", append = True, inplace = True)
ecg_hr_features_v2.head()

                                              ecg_heart_rate
Participant type context        Datetime_sub
0001        2D   StartEndBuffer 00:00:00           59.055118
                                00:00:05           61.374795
                                00:00:10           63.184499
                                00:00:15           62.761506
                                00:00:20           73.529412

In [203]:
ecg_hrv_features_v2 = ecg_hrv_features.copy()
ecg_hrv_features_v2.reset_index("Datetime_sub", inplace = True)
ecg_hrv_features_v2["Datetime_sub"] = ecg_hrv_features_v2["Datetime_sub"] / np.timedelta64(1, 's')
ecg_hrv_features_v2['Datetime_sub'] = np.round(ecg_hrv_features_v2['Datetime_sub'])
ecg_hrv_features_v2['Datetime_sub'] = pd.to_timedelta(ecg_hrv_features_v2['Datetime_sub'], unit = 's')
# ecg_hr_features_v2.head()
ecg_hrv_features_v2.set_index("Datetime_sub", append = True, inplace = True)
ecg_hrv_features_v2.head()

                                              ecg_hrv_std
Participant type context        Datetime_sub
0001        2D   StartEndBuffer 00:00:00        63.711190
                                00:00:20        62.696710
                                00:00:40        55.093781
                                00:01:00        45.139898
                                00:01:20        90.796952

In [206]:
def change_events(df, log_events, time_window):
    df = df.reset_index("context")
    s = [str(x).replace('Start','') for x in df['context'].values]
    s = [str(x).replace('Stop','') for x in s]
    s = [str(x).replace('nan','Garbage') for x in s]
    df['context'] = s
    df = df[df['context']!="FrontBuffer"]
    df = df[df['context']!="EndBuffer"]
    df = df.reset_index().set_index(["Participant","type","context","Datetime_sub"])
    return df

In [276]:
features_dataframe = {"ecg_hr":ecg_hr_features, "ecg_std":ecg_hrv_features, "skt":skin_temperature, "eda":eda_features}
time_windows = {"ecg_hr":"5s", "ecg_std":"20s", "skt":"10s", "eda": "30s"}
all_features = pd.DataFrame([])
flag = False
for index, data in features_dataframe.items():
    print(index)
    t = time_windows[index]
    f = change_events(data, log_events, t)
    display(f.head())

ecg_hr

                                       ecg_heart_rate
Participant type context Datetime_sub
0001        2D   HH      00:00:00           66.568047
                         00:00:05           68.545316
                         00:00:10           65.104167
                         00:00:15           61.425061
                         00:00:20           65.502183

ecg_std

                                       ecg_hrv_std
Participant type context Datetime_sub
0001        2D   HH      00:00:00        60.411289
                         00:00:20        82.040176
                         00:00:40        83.371593
                         00:01:00       111.385606
                         00:01:20        68.275632

skt

                                       skin_temperature
Participant type context Datetime_sub
0001        2D   HH      00:00:00             12.959742
                         00:00:10             12.962748
                         00:00:20             12.959219
                         00:00:30             12.969762
                         00:00:40             12.963512

eda

                                       eda_mean  eda_no_of_peaks    eda_lf  \
Participant type context Datetime_sub
0001        2D   HH      00:00:00      3.248435                6  0.000444
                         00:00:30      2.994607                9  0.001145
                         00:01:00      2.745352                4  0.001074
                         00:01:30      2.567717               11  0.001928
                         00:02:00      2.327562                2  0.000075

                                         eda_hf  eda_lf_hf_ratio
Participant type context Datetime_sub
0001        2D   HH      00:00:00      0.000203         2.186737
                         00:00:30      0.000660         1.736156
                         00:01:00      0.000334         3.215840
                         00:01:30      0.001121         1.719340
                         00:02:00      0.000062         1.212903

In [323]:
all_features = ecg_hr_features.merge(ecg_hrv_features, how = "left", right_index = True, left_index = True)
all_features.head()

                                              ecg_heart_rate  ecg_hrv_std
Participant type context        Datetime_sub
0001        2D   StartEndBuffer 00:00:00           59.055118    70.691281
                                00:00:05           61.813187          NaN
                                00:00:10           62.866723          NaN
                                00:00:15           64.655172          NaN
                                00:00:20           74.196208    64.967976

In [324]:
all_features = all_features.merge(skin_temperature, how = "left", right_index = True, left_index = True)
all_features.head()

                                              ecg_heart_rate  ecg_hrv_std  \
Participant type context        Datetime_sub
0001        2D   StartEndBuffer 00:00:00           59.055118    70.691281
                                00:00:05           61.813187          NaN
                                00:00:10           62.866723          NaN
                                00:00:15           64.655172          NaN
                                00:00:20           74.196208    64.967976

                                              skin_temperature
Participant type context        Datetime_sub
0001        2D   StartEndBuffer 00:00:00             12.967830
                                00:00:05                   NaN
                                00:00:10             12.959119
                                00:00:15                   NaN
                                00:00:20             12.959495

In [325]:
all_features = all_features.merge(eda_features, how = "left", right_index = True, left_index = True)
all_features.head(20)

                                              ecg_heart_rate  ecg_hrv_std  \
Participant type context        Datetime_sub
0001        2D   StartEndBuffer 00:00:00           59.055118    70.691281
                                00:00:05           61.813187          NaN
                                00:00:10           62.866723          NaN
                                00:00:15           64.655172          NaN
                                00:00:20           74.196208    64.967976
                                00:00:25           69.821567          NaN
                                00:00:30           66.617321          NaN
                                00:00:35           65.160730          NaN
                                00:00:40           66.371681    55.276714
                                00:00:45           66.195940          NaN
                                00:00:50           62.240664          NaN
                                00:00:55           68.912711          NaN
                                00:01:00           63.721325    48.497066
                                00:01:05           62.630480          NaN
                                00:01:10           62.656642          NaN
                                00:01:15           68.493151          NaN
                                00:01:20           71.315372    91.838782
                                00:01:25           64.655172          NaN
                                00:01:30           61.983471          NaN
                                00:01:35           63.667233          NaN

                                              skin_temperature  eda_mean  \
Participant type context        Datetime_sub
0001        2D   StartEndBuffer 00:00:00             12.967830  3.677715
                                00:00:05                   NaN       NaN
                                00:00:10             12.959119       NaN
                                00:00:15                   NaN       NaN
                                00:00:20             12.959495       NaN
                                00:00:25                   NaN       NaN
                                00:00:30             12.967094  5.122383
                                00:00:35                   NaN       NaN
                                00:00:40             12.966464       NaN
                                00:00:45                   NaN       NaN
                                00:00:50             12.965647       NaN
                                00:00:55                   NaN       NaN
                                00:01:00             12.960377  5.102888
                                00:01:05                   NaN       NaN
                                00:01:10             12.968769       NaN
                                00:01:15                   NaN       NaN
                                00:01:20             12.956329       NaN
                                00:01:25                   NaN       NaN
                                00:01:30             12.965784  5.220675
                                00:01:35                   NaN       NaN

                                              eda_no_of_peaks    eda_lf  \
Participant type context        Datetime_sub
0001        2D   StartEndBuffer 00:00:00                  6.0  0.037592
                                00:00:05                  NaN       NaN
                                00:00:10                  NaN       NaN
                                00:00:15                  NaN       NaN
                                00:00:20                  NaN       NaN
                                00:00:25                  NaN       NaN
                                00:00:30                  4.0  0.001944
                                00:00:35                  NaN       NaN
                                00:00:40                  NaN       NaN
                                00:00:45                  NaN       NaN
                                00:00:50                  NaN       NaN
                                00:00:55                  NaN       NaN
                                00:01:00                  3.0  0.007135
                                00:01:05                  NaN       NaN
                                00:01:10                  NaN       NaN
                                00:01:15                  NaN       NaN
                                00:01:20                  NaN       NaN
                                00:01:25                  NaN       NaN
                                00:01:30                  7.0  0.006044
                                00:01:35                  NaN       NaN

                                                eda_hf  eda_lf_hf_ratio
Participant type context        Datetime_sub
0001        2D   StartEndBuffer 00:00:00      0.023888         1.573690
                                00:00:05           NaN              NaN
                                00:00:10           NaN              NaN
                                00:00:15           NaN              NaN
                                00:00:20           NaN              NaN
                                00:00:25           NaN              NaN
                                00:00:30      0.000539         3.608991
                                00:00:35           NaN              NaN
                                00:00:40           NaN              NaN
                                00:00:45           NaN              NaN
                                00:00:50           NaN              NaN
                                00:00:55           NaN              NaN
                                00:01:00      0.002519         2.832421
                                00:01:05           NaN              NaN
                                00:01:10           NaN              NaN
                                00:01:15           NaN              NaN
                                00:01:20           NaN              NaN
                                00:01:25           NaN              NaN
                                00:01:30      0.003774         1.601694
                                00:01:35           NaN              NaN

In [326]:
# all_features.drop("context",axis = 1, inplace = True)
all_features.reset_index("context", inplace = True)
s = [str(x).replace('Start','') for x in all_features['context'].values]
s = [str(x).replace('Stop','') for x in s]
s = [str(x).replace('nan','Garbage') for x in s]
all_features['context'] = s
all_features = all_features[all_features["context"]!="EndBuffer"]
all_features = all_features[all_features['context']!="FrontBuffer"]
all_features = all_features.reset_index().set_index(["Participant","type","context","Datetime_sub"])
all_features.head()

                                       ecg_heart_rate  ecg_hrv_std  \
Participant type context Datetime_sub
0001        2D   HH      00:00:00           66.568047    60.411289
                         00:00:05           68.545316          NaN
                         00:00:10           65.104167          NaN
                         00:00:15           61.425061          NaN
                         00:00:20           65.502183    82.040176

                                       skin_temperature  eda_mean  \
Participant type context Datetime_sub
0001        2D   HH      00:00:00             12.959742  3.248435
                         00:00:05                   NaN       NaN
                         00:00:10             12.962748       NaN
                         00:00:15                   NaN       NaN
                         00:00:20             12.959219       NaN

                                       eda_no_of_peaks    eda_lf    eda_hf  \
Participant type context Datetime_sub
0001        2D   HH      00:00:00                  6.0  0.000444  0.000203
                         00:00:05                  NaN       NaN       NaN
                         00:00:10                  NaN       NaN       NaN
                         00:00:15                  NaN       NaN       NaN
                         00:00:20                  NaN       NaN       NaN

                                       eda_lf_hf_ratio
Participant type context Datetime_sub
0001        2D   HH      00:00:00             2.186737
                         00:00:05                  NaN
                         00:00:10                  NaN
                         00:00:15                  NaN
                         00:00:20                  NaN

In [327]:
joblib.dump(all_features,"/mnt/shared_drive/data/brain_therapy/new_features.pkl")

['/mnt/shared_drive/data/brain_therapy/new_features.pkl']

In [330]:
d = all_features.copy()
d.head()

                                       ecg_heart_rate  ecg_hrv_std  \
Participant type context Datetime_sub
0001        2D   HH      00:00:00           66.568047    60.411289
                         00:00:05           68.545316          NaN
                         00:00:10           65.104167          NaN
                         00:00:15           61.425061          NaN
                         00:00:20           65.502183    82.040176

                                       skin_temperature  eda_mean  \
Participant type context Datetime_sub
0001        2D   HH      00:00:00             12.959742  3.248435
                         00:00:05                   NaN       NaN
                         00:00:10             12.962748       NaN
                         00:00:15                   NaN       NaN
                         00:00:20             12.959219       NaN

                                       eda_no_of_peaks    eda_lf    eda_hf  \
Participant type context Datetime_sub
0001        2D   HH      00:00:00                  6.0  0.000444  0.000203
                         00:00:05                  NaN       NaN       NaN
                         00:00:10                  NaN       NaN       NaN
                         00:00:15                  NaN       NaN       NaN
                         00:00:20                  NaN       NaN       NaN

                                       eda_lf_hf_ratio
Participant type context Datetime_sub
0001        2D   HH      00:00:00             2.186737
                         00:00:05                  NaN
                         00:00:10                  NaN
                         00:00:15                  NaN
                         00:00:20                  NaN

In [ ]:
all_features.rese

In [339]:
all_features = all_features.reset_index("Datetime_sub").groupby(["Participant","type","context"], as_index = False).apply(lambda x: x.head())

In [348]:
all_features = all_features.reset_index().drop("level_0", axis = 1).\
        rename(columns = {"Datetime_sub":"Datetime","type":"Type"}).set_index(["Participant","Type","context","Datetime"])

In [332]:
x = d.groupby(["Participant","type","context",]).apply(lambda x: x.head(24))

In [333]:
x.head()

                                                                ecg_heart_rate  \
Participant type context Participant type context Datetime_sub
0001        2D   HH      0001        2D   HH      00:00:00           66.568047
                                                  00:00:05           68.545316
                                                  00:00:10           65.104167
                                                  00:00:15           61.425061
                                                  00:00:20           65.502183

                                                                ecg_hrv_std  \
Participant type context Participant type context Datetime_sub
0001        2D   HH      0001        2D   HH      00:00:00        60.411289
                                                  00:00:05              NaN
                                                  00:00:10              NaN
                                                  00:00:15              NaN
                                                  00:00:20        82.040176

                                                                skin_temperature  \
Participant type context Participant type context Datetime_sub
0001        2D   HH      0001        2D   HH      00:00:00             12.959742
                                                  00:00:05                   NaN
                                                  00:00:10             12.962748
                                                  00:00:15                   NaN
                                                  00:00:20             12.959219

                                                                eda_mean  \
Participant type context Participant type context Datetime_sub
0001        2D   HH      0001        2D   HH      00:00:00      3.248435
                                                  00:00:05           NaN
                                                  00:00:10           NaN
                                                  00:00:15           NaN
                                                  00:00:20           NaN

                                                                eda_no_of_peaks  \
Participant type context Participant type context Datetime_sub
0001        2D   HH      0001        2D   HH      00:00:00                  6.0
                                                  00:00:05                  NaN
                                                  00:00:10                  NaN
                                                  00:00:15                  NaN
                                                  00:00:20                  NaN

                                                                  eda_lf  \
Participant type context Participant type context Datetime_sub
0001        2D   HH      0001        2D   HH      00:00:00      0.000444
                                                  00:00:05           NaN
                                                  00:00:10           NaN
                                                  00:00:15           NaN
                                                  00:00:20           NaN

                                                                  eda_hf  \
Participant type context Participant type context Datetime_sub
0001        2D   HH      0001        2D   HH      00:00:00      0.000203
                                                  00:00:05           NaN
                                                  00:00:10           NaN
                                                  00:00:15           NaN
                                                  00:00:20           NaN

                                                                eda_lf_hf_ratio
Participant type context Participant type context Datetime_sub
0001        2D   HH      0001        2D   HH      00:00:00             2.186737
                                                  00:00:05                  NaN
                                                  00:00:10                  NaN
                                                  00:00:15                  NaN
                                                  00:00:20                  NaN